# Generated by Django 4.2 on 2024-01-22 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("imageApp", "0004_remove_imagemodel_grayscale_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagemodel",
            name="grayscale_image",
        ),
        migrations.RemoveField(
            model_name="imagemodel",
            name="image",
        ),
        migrations.AddField(
            model_name="imagemodel",
            name="result_image",
            field=models.ImageField(blank=True, null=True, upload_to="result_images/"),
        ),
        migrations.AddField(
            model_name="imagemodel",
            name="watch_image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="uploaded_images/"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="imagemodel",
            name="wrist_image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="uploaded_images/"
            ),
            preserve_default=False,
        ),
    ]
